name: QA review

on:
  push:
    branches-ignore:
      - master
      - staging
      - develop

jobs:
  check:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.6.x
      - name: NPM install
        run: npm install
      - name: QA check
        run: |
          npm run cypress:check
      - name: Notification to slack
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
